name: midi_io_platform_interface
description: Platform interface for the Midi IO plugin
version: 1.0.1
homepage: https://patchr.app
repository: https://github.com/patchr-app/flutter_midi/tree/main/midi_io_platform_interface

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.9.1+hotfix.4"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
